### ISSUE TITLE
Deployable to Heroku Directly

### ISSUE THREAD

**Issue by alagu** [alagu/pagoda#14]
Hey Guys,

Didn't know how to communicate via Github, so creating a issue. You could now checkout pagoda and deploy your blog to heroku (could be github, bitbucket or even locally hosted)

``` bash
git clone https://github.com/alagu/pagoda
cd pagoda
heroku create
git push heroku master
bundle exec rake heroku
```

Tagging @gms8994, @joshstrange, @swatto, @jbleuzen, @jamesanderson and @tealtan for feedback

**Comment by alagu** [comment]
Please leave your comments or let me know if I shouldn't include you for feedback :)

**Comment by jbleuzen** [comment]
Hi alagu.
For me it's working, but as a heroku noob didn't find a way to setup my HTTP BASIC AUTH credentials...
Maybe you should add a little documentation on how to do that cause admin/admin doesn't seem to be valid... 

I tried to set with these commands but didn't work 

``` bash
$> heroku config:add LOGIN_USER=johan
$> heroku config:add LOGIN_PASS=`echo "johan" | md5`
```

And by the way, the demo is also asking fot http basic credentials but admin/admin is not working.

**Comment by captn3m0** [comment]
The command is `heroku config:set` not `heroku config:add`
