### ISSUE TITLE
"bundle exec rake heroku" throws up further configuration options

### ISSUE THREAD

**Issue by benedfit** [alagu/pagoda#15]
Can anyone advise a Heroku n00b with further steps to deploy after running "bundle exec rake heroku"?

**Comment by alagu** [comment]
Hey benedfit. 

It does throw up options. Let me help you with it:

```
Configuring Heroku for you
Enter your repository url (e.g git@bitbucket.org:alagu/private-blog.git): (1)
Pick a Username: (2)
Enter a password:  (3)******
Heroku configuration Done.
Copy this ssh public key to github or bitbucket or your git remote (also saved in ~/.ssh/pagoda-key.pub)

(4) ssh-rsa  <<rsa-key>>


Visit http://vast-eyrie-3335.herokuapp.com/ and login with the above given Username & Password

```

You have to enter 3 items. 
1. Your git repository (git@github.com:name/repo.git)
2. An username to login
3. Password for the same

Once you are done, you should push it to heroku (git push heroku master)

After that, add (4) to your ssh keys in your repository host (github/bitbucket).

That should be it. Then you can access your blog in the above mentioned URL (you have to add a /admin)!

**Comment by alagu** [comment]
If you have a specific blog, I can help you set it up.

**Comment by benedfit** [comment]
Yeah advise on setup would be appreciated. I'm currently set up as follows:
- Bitbucket repo that contains folder named source that contains my Jekyll
  layouts etc, which is generated into a folder called _deploy
- The contents of _deploy is then pushed to a Github repo and hosted via
  Github Pages

How would you advise changing this structure to best work with Pagoda? I'm
also a little confused about what is actually pushed to Heroku. Is this
just the admin system? Or will my whole site then be running on Heroku?

Cheers

Ben

**Comment by alagu** [comment]
Hey @benedfit 

Your structure is perfect for working with Pagoda, it doesn't need to change at all. Just the admin system is pushed to pagoda. Any changes you make on the admin system would be pushed to your bitbucket instance. So there is nothing stored there.

You could retain your site as is. Currently in between something, I'll get back to you soon on this.

-Alagu

**Comment by alagu** [comment]
Hey @benedfit, I'm closing this issue - let me know if you need any help with setting it up.
