### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by stephenway** [alagu/pagoda#16]
I was wondering if there were any plans to bring page editing to this project? From the demo it seems there is only post editing.

**Comment by alagu** [comment]
This is an interesting usecase. I still haven't thought about how the UX for page editing should look like. WIll think more about it. 

Aside, are you using this project live?

**Comment by stephenway** [comment]
Not yet, but I'm seriously considering it. I have a slew of static sites that need an interface for clients and so far this seems to be the easiest to use. Page editing would definitely help my clients iterate on their content.

**Comment by alagu** [comment]
I would be happy to help you with it. Which version of Jekyll do you use?

**Comment by stephenway** [comment]
Thanks! I believe I'm on 1.2.0

**Comment by BenBish** [comment]
Pages would pretty much put the icing on the cake for Pagoda! I have this running locally and really like the way it works.

**Comment by alagu** [comment]
I'm definitely going to build this. Just stuck up on time right now. Will get on to this as soon as my hands are free.
