### ISSUE TITLE
Configuration for posts folder location

### ISSUE THREAD

**Issue by tealtan** [alagu/pagoda#2]
The default directory for posts is /_posts, but I keep mine under /writing/_posts. Is there a way to make that a config option?

**Comment by alagu** [comment]
Hey @tealtan, no configuration yet. Could you give me a pull request for it?

**Comment by tealtan** [comment]
Never mind – I just found out about [permalinks in Jekyll](http://jekyllrb.com/docs/permalinks/), so I can use that instead!
