### ISSUE TITLE
Yaml editor

### ISSUE THREAD

**Issue by Swatto** [alagu/pagoda#4]
It could be great to have the possibilities to modify the yaml information of the post in pagoda.

For example, I write a jekyll website for a friends who can list picture or youtube's video id and the views is generated.

With that kind of feature, she can left the editor and write it in a single place. :love_letter:

**Comment by alagu** [comment]
Agreed. There should be a YAML key-value editor in the edit area.

**Comment by gms8994** [comment]
Leaving my comment here for a +1.

**Comment by alagu** [comment]
Just a curiosity @gms8994 , I see lot of new people starring this project today, could you tell me where you heard about this project?

About the YAML editor, I'm working on it.

**Comment by gms8994** [comment]
I saw it on http://onethingwell.org/post/52140522858/pagoda

**Comment by gglanzani** [comment]
+1 (both for onethingwell as well for the Yaml editor).

Is it still on your TODO list?

**Comment by alagu** [comment]
Yes. It is already WIP in another branch. 

​

 

—

**Comment by alagu** [comment]
Hello, I've pushed a new version with YAML editor. Would love your feedback, @gglanzani, @gms8994 and @swatto.

**Comment by Swatto** [comment]
Awesome ! but inputs for values could be bigger : that's small for arrays I think.
Great works indeed !

**Comment by alagu** [comment]
Increased the size of values a bit.

**Comment by gms8994** [comment]
@alagu The only problem I have is that when writing an array to the file, the  values written look like

```
tags: ! ["tag1","tag2","tag3"]
```

I'm not sure if it's Jekyll v1 specific or not, but it won't parse those, and throws an error. An option to have them listed like

```
tags:
 - tag1
 - tag2
 - tag3
```

would be excellent.
