### ISSUE TITLE
Default yaml structure

### ISSUE THREAD

**Issue by Swatto** [alagu/pagoda#9]
Thanks for the yaml editor that you made. This is so cool ! :+1: 

Next step is to let us configure the default structure of these.
Like a file that have all values we need in our page to work properly and let the end-user change them with the needed values for the content that he write.

I think of that for poeple who I helped them to build their website (like portfolio) who are designer, not programmer. They can give youtube, vimeo's id or picture file's name or whatever in the yaml header before the explanation of the project. Then the page is built with the content that the user specify.

It could be great for us to create a yaml structure for our users.

What do you think about it ?

**Comment by alagu** [comment]
This is an absolute need. I'm thinking to add it to the settings page.

**Comment by alagu** [comment]
You could create a _default.yml in your jekyll repo, which will be read by pagoda.

**Comment by Swatto** [comment]
Nice ! :+1:

**Comment by alagu** [comment]
Thanks!
